Repository eu-federation-gateway-service/efgs-federation-gateway, pull requests merged in 2020-09, with the labels that each got.

#76 Fix openssl option name (`outkey` -> `keyout`)
  docs/software-design-federation-gateway-service.md
Labels: in review

#81 *feat: Base64 decoding of Certificate-Hash header
  src/main/java/eu/interop/federationgateway/filter/CertificateAuthentificationFilter.java
  src/test/java/eu/interop/federationgateway/filter/CertAuthFilterTest.java
Labels: enhancement

#95 Feat: Input-Validator for DiagnosisKeys
  src/main/java/eu/interop/federationgateway/config/ErrorHandler.java
  src/main/java/eu/interop/federationgateway/controller/UploadController.java
  src/main/java/eu/interop/federationgateway/validator/DiagnosisKeyBatchConstraint.java
  src/main/java/eu/interop/federationgateway/validator/DiagnosisKeyBatchValidator.java
  src/test/java/eu/interop/federationgateway/controller/AuditControllerTest.java
  src/test/java/eu/interop/federationgateway/controller/UploadControllerTest.java
  src/test/java/eu/interop/federationgateway/validator/DiagnosisKeyBatchValidatorTest.java
Labels: enhancement

#103 Feat: Audit-download will be requested with date and batchtag
  src/main/java/eu/interop/federationgateway/controller/AuditController.java
  src/main/java/eu/interop/federationgateway/repository/DiagnosisKeyEntityRepository.java
  src/main/java/eu/interop/federationgateway/service/DiagnosisKeyEntityService.java
  src/test/java/eu/interop/federationgateway/controller/AuditControllerTest.java
Labels: enhancement

#105 Fix: update openapi.json
  docs/openapi.json
Labels: enhancement

#117 fix: Wrong Isolation Level for DiagnosisKeyEntityRepository
  src/main/java/eu/interop/federationgateway/repository/DiagnosisKeyEntityRepository.java
Labels: enhancement

#116 feat: callback mtls and TrustAnchor
  .gitignore
  docs/openapi.json
  src/main/java/eu/interop/federationgateway/batchsigning/BatchSignatureVerifier.java
  src/main/java/eu/interop/federationgateway/config/EfgsKeyStore.java
  src/main/java/eu/interop/federationgateway/config/EfgsProperties.java
  src/main/java/eu/interop/federationgateway/config/WebClientConfig.java
  src/main/java/eu/interop/federationgateway/controller/AuditController.java
  src/main/java/eu/interop/federationgateway/controller/UploadController.java
  src/main/java/eu/interop/federationgateway/entity/CertificateEntity.java
  src/main/java/eu/interop/federationgateway/entity/UploaderInformation.java
  src/main/java/eu/interop/federationgateway/mapper/DiagnosisKeyMapper.java
  src/main/java/eu/interop/federationgateway/model/AuditEntry.java
  src/main/java/eu/interop/federationgateway/mtls/EfgsCallbackTrustManager.java
  src/main/java/eu/interop/federationgateway/mtls/ForceCertUsageX509KeyManager.java
  src/main/java/eu/interop/federationgateway/repository/CertificateRepository.java
  src/main/java/eu/interop/federationgateway/repository/DiagnosisKeyEntityRepository.java
  src/main/java/eu/interop/federationgateway/service/CallbackService.java
  src/main/java/eu/interop/federationgateway/service/CallbackTaskExecutorService.java
  src/main/java/eu/interop/federationgateway/service/CertificateService.java
  src/main/java/eu/interop/federationgateway/utils/CertificateUtils.java
  src/main/resources/application.yml
  src/main/resources/db/changelog.yml
  src/main/resources/db/changelog/v001-add-certificate-entity-signature-and-rawdata.yml
  src/main/resources/db/changelog/v001-add-diagnosis-key-entity-signingcertthumbprint.yml
  src/test/java/eu/interop/federationgateway/TestData.java
  src/test/java/eu/interop/federationgateway/batchsigning/BatchSignatureVerifierTest.java
  src/test/java/eu/interop/federationgateway/batchsigning/DiagnosisKeyBatchAndSignatureGeneratorTest.java
  src/test/java/eu/interop/federationgateway/batchsigning/SignatureGenerator.java
  src/test/java/eu/interop/federationgateway/controller/AuditControllerTest.java
  src/test/java/eu/interop/federationgateway/controller/CallbackAdminControllerTest.java
  src/test/java/eu/interop/federationgateway/controller/DownloadControllerTest.java
  src/test/java/eu/interop/federationgateway/controller/UploadControllerTest.java
  src/test/java/eu/interop/federationgateway/filter/CertAuthFilterTest.java
  src/test/java/eu/interop/federationgateway/mapper/DiagnosiskeyMapperTest.java
  src/test/java/eu/interop/federationgateway/mtls/EfgsCallbackTrustManagerTest.java
  src/test/java/eu/interop/federationgateway/service/CallbackServiceTest.java
  src/test/java/eu/interop/federationgateway/service/CallbackTaskExecutorServiceTest.java
  src/test/java/eu/interop/federationgateway/service/CertificateServiceTest.java
  src/test/java/eu/interop/federationgateway/service/DiagnosisKeyCleanupServiceTest.java
  src/test/java/eu/interop/federationgateway/testconfig/EfgsTestKeyStore.java
  src/test/java/eu/interop/federationgateway/testdata/TestDataGenerator.java
  src/test/java/eu/interop/federationgateway/validator/DiagnosisKeyBatchValidatorTest.java
  src/test/resources/application.yml
Labels: enhancement

#128 Fix: Input-Validator accepts a rolling-start-interval with value 0
  src/main/java/eu/interop/federationgateway/validator/DiagnosisKeyBatchValidator.java
Labels: bug

#125 fix: Callback Exception when more then one callback is pending
  src/main/java/eu/interop/federationgateway/repository/CallbackTaskRepository.java
  src/main/java/eu/interop/federationgateway/service/CallbackTaskExecutorService.java
  src/test/java/eu/interop/federationgateway/service/CallbackTaskExecutorServiceTest.java
Labels: bug

#124 Added Unit-Tests to improve cert manipulation security
  src/test/java/eu/interop/federationgateway/controller/UploadControllerTest.java
  src/test/java/eu/interop/federationgateway/service/CertificateServiceTest.java
Labels: enhancement

#108 fix: Extract options-endpoint from upload and download to [OPTIONS] /diagnosiskeys
  docs/openapi.json
  src/main/java/eu/interop/federationgateway/controller/DiagnosisKeyController.java
  src/main/java/eu/interop/federationgateway/controller/DownloadController.java
  src/main/java/eu/interop/federationgateway/controller/UploadController.java
  src/test/java/eu/interop/federationgateway/controller/DiagnosisKeyControllerTest.java
  src/test/java/eu/interop/federationgateway/controller/DownloadControllerTest.java
  src/test/java/eu/interop/federationgateway/controller/UploadControllerTest.java
Labels: bug

#131 feat: DiagnosisKey encryption in database
  src/main/java/eu/interop/federationgateway/config/EfgsProperties.java
  src/main/java/eu/interop/federationgateway/config/EfgsPropertiesValidator.java
  src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionByteArrayConverter.java
  src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionIntConverter.java
  src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionReportTypeConverter.java
  src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionService.java
  src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionStringConverter.java
  src/main/java/eu/interop/federationgateway/entity/DiagnosisKeyPayload.java
  src/main/java/eu/interop/federationgateway/repository/DiagnosisKeyEntityRepository.java
  src/main/java/eu/interop/federationgateway/service/DiagnosisKeyEntityService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/db/changelog.yml
  src/main/resources/db/changelog/v001-update-diagnosiskeypayload_encryption.yml
  src/test/java/eu/interop/federationgateway/dbencryption/DbEncryptionTest.java
  src/test/java/eu/interop/federationgateway/repository/DiagnosisKeyEntityRepositoryTest.java
  src/test/java/eu/interop/federationgateway/service/DiagnosisKeyEntityServiceTest.java
  src/test/resources/application.yml
Labels: enhancement

#138 fix: Update Http 400 Status openApi.json for Download and Audit
  docs/openapi.json
  src/main/java/eu/interop/federationgateway/controller/AuditController.java
  src/main/java/eu/interop/federationgateway/controller/DownloadController.java
Labels: bug

#126 Publish latest docker image in GitHub Docker registry
  .github/workflows/ci-master.yml
Labels: in review

#140 feat: Log message documentation for cert integrity check
  docs/software-design-federation-gateway-service.md
  src/main/java/eu/interop/federationgateway/service/CertificateService.java
Labels: enhancement

#145 fix: Return number of possibly inserted keys on upload failure.
  src/main/java/eu/interop/federationgateway/service/DiagnosisKeyEntityService.java
  src/test/java/eu/interop/federationgateway/controller/UploadControllerTest.java
  src/test/java/eu/interop/federationgateway/service/DiagnosisKeyEntityServiceTest.java
Labels: bug

#143 Swap conditions according to methods called inside
  src/test/java/eu/interop/federationgateway/batchsigning/SignatureGenerator.java
Labels: code improvement

#142 feat: Disable Swagger Endpoint for PRD
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: enhancement

#144 feat: add diagnosis-key-entity-table-indexes
  src/main/resources/db/changelog.yml
  src/main/resources/db/changelog/v001-add-diagnosis-key-entity-indexes.yml
Labels: enhancement

#146 fixed several sonarcube bugs
  src/main/java/eu/interop/federationgateway/FederationGatewayApplication.java
  src/main/java/eu/interop/federationgateway/batchsigning/BatchSignatureUtils.java
  src/main/java/eu/interop/federationgateway/batchsigning/BatchSignatureVerifier.java
  src/main/java/eu/interop/federationgateway/config/EfgsKeyStore.java
  src/main/java/eu/interop/federationgateway/config/ProtobufHttpMessageConverter.java
  src/main/java/eu/interop/federationgateway/controller/DownloadController.java
  src/main/java/eu/interop/federationgateway/entity/CallbackSubscriptionEntity.java
  src/main/java/eu/interop/federationgateway/filter/CertificateAuthentificationFilter.java
  src/main/java/eu/interop/federationgateway/service/DiagnosisKeyBatchService.java
  src/main/java/eu/interop/federationgateway/service/TransactionalDiagnosisKeyBatchService.java
  src/main/java/eu/interop/federationgateway/utils/CertificateUtils.java
  src/main/java/eu/interop/federationgateway/utils/EfgsMdc.java
  src/main/java/eu/interop/federationgateway/utils/SemVerUtils.java
  src/test/java/eu/interop/federationgateway/service/DiagnosisKeyBatchServiceTest.java
Labels: code improvement

#148 fix: Keystore loading
  src/main/java/eu/interop/federationgateway/config/EfgsKeyStore.java
Labels: bug

#157 fix: time zones is UTC
  src/main/java/eu/interop/federationgateway/controller/DownloadController.java
Labels: bug

#160 fix: Fixed the deadlock on app initialization when using tomcat
  src/main/java/eu/interop/federationgateway/config/EfgsProperties.java
  src/main/java/eu/interop/federationgateway/config/EfgsPropertiesValidator.java
  src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionByteArrayConverter.java
  src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionIntConverter.java
  src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionReportTypeConverter.java
  src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionService.java
  src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionStringConverter.java
  src/main/resources/application.yml
Labels: bug

#162 doc: update software-design-federation-gateway-service.md
  docs/software-design-federation-gateway-service.md
Labels: documentation

#173 doc: sonarcloud metric report
  README.md
Labels: documentation
