Repository eu-federation-gateway-service/efgs-federation-gateway, pull requests merged in 2020-10, with the labels that each got.

#174 doc: clean up some error messages
  docs/software-design-federation-gateway-service.md
Labels: documentation

#183 fix: Maven plugin 'maven-surefire-plugin' warning
  pom.xml
Labels: in review

#181 feat: disabling actuator endpoints
  .github/workflows/manual-package.yml
  src/main/resources/application.yml
Labels: bug

#163 fix: NotBefore Property of CallbackTask is wrong
  src/main/java/eu/interop/federationgateway/repository/CallbackTaskRepository.java
  src/main/java/eu/interop/federationgateway/service/CallbackService.java
  src/test/java/eu/interop/federationgateway/service/CallbackServiceTest.java
Labels: bug

#198 fix: AuditEntry and midnight
  src/main/java/eu/interop/federationgateway/config/EfgsProperties.java
  src/main/java/eu/interop/federationgateway/service/DiagnosisKeyEntityService.java
  src/test/java/eu/interop/federationgateway/controller/AuditControllerTest.java
  src/test/java/eu/interop/federationgateway/service/DiagnosisKeyEntityServiceTest.java
Labels: bug

#201 make tools scripts executable
  tools/create_callback_client_certificate.bat
  tools/create_callback_client_certificate.sh
  tools/create_certificate_signature.bat
  tools/create_certificate_signature.sh
  tools/create_trustanchor.bat
  tools/create_trustanchor.sh
Labels: 1st Prio - High

#212 fix: Leading zero in cert thumbprint leads to error
  src/main/java/eu/interop/federationgateway/filter/CertificateAuthentificationFilter.java
  src/test/java/eu/interop/federationgateway/filter/CertAuthFilterTest.java
Labels: 1st Prio - High, bug

#213 fix: Log Statement for download reports not reliable number of downloads
  docs/software-design-federation-gateway-service.md
  src/main/java/eu/interop/federationgateway/controller/DownloadController.java
Labels: bug

#227 fix: visited countries array contains empty string if visited countries is empty
  pom.xml
  src/main/java/eu/interop/federationgateway/mapper/DiagnosisKeyMapper.java
  src/test/java/eu/interop/federationgateway/mapper/DiagnosiskeyMapperTest.java
Labels: bug
