Repository eu-federation-gateway-service/efgs-federation-gateway, pull requests merged in 2020-11, with the labels that each got.

#238 fix: Audit Endpoint wrong order
  owasp/suppressions.xml
  src/main/java/eu/interop/federationgateway/model/AuditEntry.java
  src/main/java/eu/interop/federationgateway/repository/DiagnosisKeyEntityRepository.java
  src/main/java/eu/interop/federationgateway/service/DiagnosisKeyEntityService.java
  src/test/java/eu/interop/federationgateway/repository/DiagnosisKeyEntityRepositoryTest.java
  src/test/java/eu/interop/federationgateway/service/DiagnosisKeyEntityServiceTest.java
Labels: bug

#236 doc: Update README.md
  README.md
Labels: documentation

#206 fix: clean code, add license header and sonar fixes
  src/main/java/eu/interop/federationgateway/batchsigning/BatchSignatureUtils.java
  src/main/java/eu/interop/federationgateway/config/EfgsKeyStore.java
  src/main/java/eu/interop/federationgateway/config/ProtobufHttpMessageConverter.java
  src/main/java/eu/interop/federationgateway/config/SchedulerConfig.java
  src/main/java/eu/interop/federationgateway/config/ShedLockConfig.java
  src/main/java/eu/interop/federationgateway/config/WebClientConfig.java
  src/main/java/eu/interop/federationgateway/controller/CallbackAdminController.java
  src/main/java/eu/interop/federationgateway/controller/DownloadController.java
  src/main/java/eu/interop/federationgateway/controller/UploadController.java
  src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionByteArrayConverter.java
  src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionIntConverter.java
  src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionReportTypeConverter.java
  src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionService.java
  src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionStringConverter.java
  src/main/java/eu/interop/federationgateway/mapper/DiagnosisKeyMapper.java
  src/main/java/eu/interop/federationgateway/mtls/EfgsCallbackTrustManager.java
  src/main/java/eu/interop/federationgateway/service/CallbackService.java
  src/main/java/eu/interop/federationgateway/service/DiagnosisKeyCleanupService.java
  src/main/java/eu/interop/federationgateway/service/DiagnosisKeyEntityService.java
  src/main/java/eu/interop/federationgateway/utils/CertificateUtils.java
  src/main/java/eu/interop/federationgateway/utils/EfgsMdc.java
  src/main/java/eu/interop/federationgateway/utils/SemVerUtils.java
  src/main/java/eu/interop/federationgateway/validator/DiagnosisKeyBatchConstraint.java
  src/main/java/eu/interop/federationgateway/validator/DiagnosisKeyBatchValidator.java
  src/test/java/eu/interop/federationgateway/batchsigning/BatchSignatureUtilsTest.java
  src/test/java/eu/interop/federationgateway/batchsigning/BatchSignatureVerifierTest.java
  src/test/java/eu/interop/federationgateway/batchsigning/SignatureGenerator.java
  src/test/java/eu/interop/federationgateway/controller/AuditControllerTest.java
  src/test/java/eu/interop/federationgateway/dbencryption/DbEncryptionTest.java
  src/test/java/eu/interop/federationgateway/mtls/EfgsCallbackTrustManagerTest.java
  src/test/java/eu/interop/federationgateway/repository/CallbackTaskRepositoryTest.java
  src/test/java/eu/interop/federationgateway/service/CallbackServiceTest.java
  src/test/java/eu/interop/federationgateway/service/CertificateServiceTest.java
  src/test/java/eu/interop/federationgateway/service/DiagnosisKeyCleanupServiceTest.java
  src/test/java/eu/interop/federationgateway/testconfig/EfgsTestKeyStore.java
  src/test/java/eu/interop/federationgateway/testdata/TestDataGenerator.java
  src/test/java/eu/interop/federationgateway/validator/DiagnosisKeyBatchValidatorTest.java
Labels: code improvement

#205 fix: Possible NPE accessing statusCode
  src/main/java/eu/interop/federationgateway/service/CallbackTaskExecutorService.java
Labels: 3rd Prio - Low, bug
