Repository eu-federation-gateway-service/efgs-federation-gateway, pull requests merged in 2020-08, with the labels that each got.

#26 doc: openapi spec
  docs/openapi.json
  pom.xml
Labels: documentation

#27 feat: sonar cloud
  .github/workflows/ci-master.yml
Labels: enhancement

#29 Removed setup of BouncyCastly provider
  src/main/java/eu/interop/federationgateway/batchsigning/BatchSignatureVerifier.java
  src/test/java/eu/interop/federationgateway/TestData.java
  src/test/java/eu/interop/federationgateway/batchsigning/SignatureGenerator.java
Labels: bug

#53 *feat: Support for MySQL 5.7
  src/main/docker/docker-compose.yml
Labels: enhancement

#51 *feat: Log-Rotation
  docs/software-design-federation-gateway-service.md
  src/main/resources/logback.xml
Labels: enhancement

#56 Added maven profile hint to readme
  README.md
Labels: documentation

#62 feat: added digit build
  pom.xml
  src/assembly/assembly.xml
Labels: enhancement

#40 Small suggestions.
  docs/software-design-federation-gateway-service.md
Labels: documentation

#67 Feat GitHub actions and remove isolation level from Liquibase
  .github/workflows/ci-master.yml
  pom.xml
  src/main/resources/db/changelog.yml
  src/main/resources/db/changelog/v000-set-transaction-isolation-level-serializable.yml
Labels: enhancement

#61 *feat: Logging properties with MDC
  docs/software-design-federation-gateway-service.md
  src/main/java/eu/interop/federationgateway/batchsigning/BatchSignatureVerifier.java
  src/main/java/eu/interop/federationgateway/config/ProtobufHttpMessageConverter.java
  src/main/java/eu/interop/federationgateway/controller/AuditController.java
  src/main/java/eu/interop/federationgateway/controller/DownloadController.java
  src/main/java/eu/interop/federationgateway/controller/UploadController.java
  src/main/java/eu/interop/federationgateway/filter/CertificateAuthentificationFilter.java
  src/main/java/eu/interop/federationgateway/service/CallbackService.java
  src/main/java/eu/interop/federationgateway/service/CallbackTaskCleanupService.java
  src/main/java/eu/interop/federationgateway/service/CallbackTaskExecutorService.java
  src/main/java/eu/interop/federationgateway/service/CertificateService.java
  src/main/java/eu/interop/federationgateway/service/DiagnosisKeyBatchService.java
  src/main/java/eu/interop/federationgateway/service/DiagnosisKeyEntityService.java
  src/main/resources/logback.xml
Labels: enhancement

#63 *fix: Data Retention for DiagnosisKeys and DiagnosisKeyBatches
  src/main/java/eu/interop/federationgateway/repository/DiagnosisKeyBatchRepository.java
  src/main/java/eu/interop/federationgateway/repository/DiagnosisKeyEntityRepository.java
  src/main/java/eu/interop/federationgateway/service/DiagnosisKeyBatchService.java
  src/main/java/eu/interop/federationgateway/service/DiagnosisKeyCleanupService.java
  src/main/java/eu/interop/federationgateway/service/DiagnosisKeyEntityService.java
  src/test/java/eu/interop/federationgateway/service/DiagnosisKeyCleanupServiceTest.java
Labels: bug

#69 Update pom.xml
  pom.xml
Labels: enhancement

#70 *fix: Cron Expression for Retention Job
  src/main/java/eu/interop/federationgateway/service/DiagnosisKeyCleanupService.java
Labels: bug
